language: java
script: mvn clean install
env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
jdk:
  - oraclejdk8

install: "/bin/true"

deploy:
  provider: heroku
  api_key:
    secure: wWPcLVF0vWdCdEwWNdw62M5ANRk3MtXtwuhToxLEIwfakxyUbp0sA28Z1v1BAV94FPybFIErZEHvPkOElQW/oeX/3ffyMgm1/Uyxd1JsebeO5ZDTko2sRHzLlMvRUVPLr4HpJPUqGS+8zaRG1c1mdEKSEGeZsEsT/E7IX0F+O1Bk7tUKC+bO26YSYoBBmUAgOFGMKHF4BRL6OnonbpIhOCCno9jAwe25ORnlqOTSgqJ9MEd86/N28fRd9ez9Sgy01gZm9iWuFcDJLSegqfcvByY3tYx6IHmJpgjKs1pXplD+txisOjQVm5Ddf+UfmQOMTN4bTxoHbwxrB23MF8Xtf7Ad+qL0WxcgzSTaQ6me0l2oGcsEzNPpTYflkVoTlI04q/fp8jqx+11w6wgVnO9mosParqZfYz7g1ooq3hgqcV7LfoFJDGpmoEier09CgLrZqXdVlt/kAGs/MaruLlFrdTdCJGQlaD/STnIzDzNEYtpvy5R3yESDUvQKK4aAMXaczvt52rgADK9czEwwjymLmY64OCakM+wTZqqa8fMJpd+YT36IjBcqh87b2AGnneJzK7qjamD1Uqn9W7HeXJ1VMGRyKel/RNY7pC82af0eS3sc3X7iKdwiuuCL/5Jq+T8Vl+GuP79gCqSTPctsPHP3N5hn3bKY099LAdbUdyfonZE=
  app: urutau-travis
  on:
    repo: tainarareis/Urutau
    branch: deploy
